/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package userinterface.ManufactureRole;

import Business.Account.UserAccount;
import Business.Disease.Disease;
import Business.Enterprise.Enterprise;
import Business.Organization.ManufactureOrganization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class ManufactureWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    ManufactureOrganization organization;
    UserAccount account;
    Enterprise enterprise;
    Business.EcoSystem s;
    /** Creates new form AdminWorkAreaJPanel */
    public ManufactureWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,ManufactureOrganization organization,Enterprise enterprise,Business.EcoSystem s) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account=account;
        this.enterprise=enterprise;
        this.s=s;
        valueLabel.setText(enterprise.getName());
        popComboBox();
    }
    
    public void popComboBox(){
        diseaseComboBox.removeAllItems();
        for(Disease d:s.getDiseaseList()){
                diseaseComboBox.addItem(d);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageCompoundJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        diseaseComboBox = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Manufacture Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        manageCompoundJButton.setText("Manage Drug");
        manageCompoundJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCompoundJButtonActionPerformed(evt);
            }
        });
        add(manageCompoundJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        diseaseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(diseaseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageCompoundJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCompoundJButtonActionPerformed

         Disease disease =(Disease) diseaseComboBox.getSelectedItem();
        ManageDrugJPanel manageDrugJPanel = new ManageDrugJPanel(userProcessContainer,disease,account,s);
        userProcessContainer.add("ManageDrugJPanel", manageDrugJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCompoundJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox diseaseComboBox;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCompoundJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
