/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Compound.Compound;
import Business.Disease.Disease;
import Business.Drug.Drug;
import Business.Study.Study;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author xss
 */
public class DiseaseKnowledgeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiseaseKnowledgeJPanel
     */
    JPanel userProcessContainer;
    Disease disease;
    EcoSystem s;
    public DiseaseKnowledgeJPanel(JPanel userProcessContainer, Disease disease, EcoSystem s) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.disease=disease;
        this.s=s;
        diseaseLabel.setText(disease.getDiseaseName());
        popGeneTable();
        populateCompoundTable();
    }


    public void popGeneTable(){
        DefaultTableModel dtm = (DefaultTableModel) geneTable.getModel();       
        dtm.setRowCount(0);
        for(Study study:disease.getStudyList().getStudyList()){           
           Object row[]=new Object[4];
           row[0]=disease.getDiseaseName();
           row[1]=study.getStudyGene();
           row[2]=study.getStudyName();
           row[3]=study.getResearcher();
           dtm.addRow(row);
        
    }
    }
    
    public void populateCompoundTable(){
        DefaultTableModel dtm = (DefaultTableModel) compoundTable.getModel();       
        dtm.setRowCount(0);
        for(Drug drug:disease.getDrugList().getDrugList()){                               
           for(Compound c:drug.getCompoundList().getCompoundList()){                         
           Object row[]=new Object[5];
           row[0]=disease.getDiseaseName();
           row[1]=drug.getDrugName();
           row[2]=drug.getManufacture();
           row[3]=c.getCompoundName();
           row[4]=c.getSupplier();
           dtm.addRow(row);                            
            }
        }    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        diseaseLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        geneTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        compoundTable = new javax.swing.JTable();

        jLabel1.setText("Disease:");

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pie Chart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        geneTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Disease", "Gene", "Study", "Researcher"
            }
        ));
        jScrollPane1.setViewportView(geneTable);

        compoundTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Disease", "Drug", "Manufacture", "Compound", "Supplier"
            }
        ));
        jScrollPane2.setViewportView(compoundTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diseaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(231, 231, 231))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diseaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(239, 239, 239))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void popluatePie(){    
        DefaultPieDataset dataset = new DefaultPieDataset();
         HashMap<String,Integer> compoundMap=new HashMap<String,Integer>();
         for(Drug drug:disease.getDrugList().getDrugList()){                               
           for(Compound c:drug.getCompoundList().getCompoundList()){     
               String name=c.getCompoundName();
               if(compoundMap.containsKey(name))
                   compoundMap.put(name, compoundMap.get(name)+1);
               else
                    compoundMap.put(name, 1);
           }
         }
           
               Iterator<String> iter=compoundMap.keySet().iterator();
               while(iter.hasNext()){
                   String coName = iter.next();
                   int num=compoundMap.get(coName);
               dataset.setValue(coName, num);
               } 
           
           JFreeChart chart=ChartFactory.createPieChart("Compound", dataset, true, true,true);
           PiePlot p=(PiePlot) chart.getPlot();
           ChartFrame frame=new ChartFrame("Compound",chart);
           DecimalFormat df = new DecimalFormat("0.00%");
           NumberFormat nf = NumberFormat.getNumberInstance();
           StandardPieSectionLabelGenerator sp1 = new StandardPieSectionLabelGenerator("{0}  {2}", nf, df);
           p.setLabelGenerator(sp1);
           frame.setVisible(true);
           frame.setSize(500,500);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:                     

        popluatePie();
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable compoundTable;
    private javax.swing.JLabel diseaseLabel;
    private javax.swing.JTable geneTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
