/*
 * AdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */

package UserInterface.DoctorRole;

import Business.Account.UserAccount;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    DoctorOrganization organization;
    UserAccount account;
    Enterprise enterprise;
    Business.EcoSystem s;
    /** Creates new form AdminWorkAreaJPanel */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer,UserAccount account,DoctorOrganization organization,Enterprise enterprise,Business.EcoSystem s) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.account=account;
        this.enterprise=enterprise;
        this.s=s;
        valueLabel.setText(account.getUserName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageCompoundJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Doctor Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        manageCompoundJButton.setText("Manage Disease");
        manageCompoundJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCompoundJButtonActionPerformed(evt);
            }
        });
        add(manageCompoundJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageCompoundJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCompoundJButtonActionPerformed

        ManageDiseaseJPanel manageDiseaseJPanel = new ManageDiseaseJPanel(userProcessContainer,account, s);
        userProcessContainer.add("manageDiseaseJPanel", manageDiseaseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCompoundJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCompoundJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
